### ISSUE TITLE
How did you decode the response? 

### ISSUE THREAD

**Issue by gmallios** [KillerBOSS2019/SoundcoreLifeAPI#9]
I am experimenting with the liberty air 2 pros using my own code https://github.com/gmallios/soundcore-rs. I am sending the same bytes as you are and receiving a 97 byte long response. I figured out the anc mode but I can't seem to figure out earbud battery and case battery( I have sample code and response in readme). Any help?
Nice project btw.

**Comment by gmallios** [comment]
Also i am using UUIDs to connect instead of ports. I found them by reversing the app and it saves a lot of time trying 31 ports. Feel free to use them.

**Comment by DamienStaebler** [comment]
If u could send me the file maybe I can dig it with Wireshark

**Comment by gmallios** [comment]
https://paste.c-net.org/WillsLorelai

**Comment by gmallios** [comment]
It sends multiple commands over SPP. I have decompiled the app and found those commands for all devices but when I send one of them I sometimes get very late response or no response. I can share the code if you need.

**Comment by gmallios** [comment]
Found the function which parses the response after sending 08ee00000001010a0002 and managed to get battery info and charging status.
![image](https://user-images.githubusercontent.com/44323649/194768057-e79b3c30-47f1-42c1-9794-446fa01a40ec.png)
